---
title: "????????????1 - ??????????????????"
output: pdf_document
---

????????? ????????? install.
```{r}
install.packages("rvest")
install.packages("xml2")
library(rvest)
library(xml2)

install.packages("dplyr")
install.packages("ggplot2")
library(dplyr)
library(ggplot2)

install.packages("ggmap")
library(ggmap)

install.packages("rworldmap")
install.packages("countrycode")

library(rworldmap)
library(countrycode)
```


????????? ???????????? 

https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita gdp2017
http://worldpopulationreview.com/countries/life-expectancy-by-country/ life expectancy2017
https://en.wikipedia.org/wiki/List_of_countries_by_suicide_rate suicide rate 2017
https://en.wikipedia.org/wiki/World_Happiness_Report happiness index 2017
https://meta.wikimedia.org/wiki/List_of_countries_by_regional_classification region 
```{r}


gdpurl<-read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita")
gdp2017<-html_table(html_nodes(gdpurl, "table")[[2]], fill=TRUE)


lifeurl<-read_html("http://worldpopulationreview.com/countries/life-expectancy-by-country/")
life2017<-html_table(html_nodes(lifeurl, "table")[[1]], fill=TRUE)


suicideurl<-read_html("https://en.wikipedia.org/wiki/List_of_countries_by_suicide_rate")
suicide2017<-html_table(html_nodes(suicideurl, "table")[[2]], fill=TRUE)


happyurl<-read_html("https://en.wikipedia.org/wiki/World_Happiness_Report")
happy2017<-html_table(html_nodes(happyurl, "table")[[5]], fill=TRUE)


regionurl<-read_html("https://meta.wikimedia.org/wiki/List_of_countries_by_regional_classification")
region2017<-html_table(html_nodes(regionurl, "table")[[1]], fill=TRUE)

```



???????????????????????? ?????? & ????????? ???????????? ????????? ?????? 
```{r}

gdp2017<-as.data.frame(gdp2017)
life2017<-as.data.frame(life2017)
suicide2017<-as.data.frame(suicide2017)
happy2017<-as.data.frame(happy2017)
region2017<-as.data.frame(region2017)


gdp2017<-gdp2017[order(gdp2017$`Country/Territory`),]
life2017<-life2017[order(life2017$Country),]
suicide2017<-suicide2017[order(suicide2017$Regions),]
happy2017<-happy2017[order(happy2017$Country),]
region2017<-region2017[order(region2017$Country),]

colnames(gdp2017)<-c("Rank", "Country", "USGDP")
colnames(suicide2017)<-c("Rank", "Country", "BothSex", "1", "2", "3", "4", "5")


gdp2017<-arrange(gdp2017, Country)
life2017<-arrange(life2017, Country)
suicide2017<-arrange(suicide2017, Country)
happy2017<-arrange(happy2017, Country)
region2017<-arrange(region2017, Country)


gdp2017<-select(gdp2017, Country, USGDP)
life2017<-select(life2017, Country, 'Life Expectancy')
suicide2017<-select(suicide2017, Country, BothSex)
region2017<-select(region2017, Country, Region)
happy2017<-select(happy2017, Country, Score)

life2017$`Life Expectancy`<-gsub("years", "", life2017$`Life Expectancy`)
life2017$`Life Expectancy`<-as.numeric(life2017$`Life Expectancy`)
gdp2017$USGDP<-gsub("\\,","", gdp2017$USGDP)
gdp2017$USGDP<-as.numeric(gdp2017$USGDP)

```


?????? code ?????????merge ???????????? + ????????? ??????
```{r}

code1<-countrycode(gdp2017$Country, 'country.name', 'iso3c')
code2<-countrycode(region2017$Country, 'country.name', 'iso3c')
code3<-countrycode(suicide2017$Country, 'country.name', 'iso3c')
code4<-countrycode(life2017$Country, 'country.name', 'iso3c')
code5<-countrycode(happy2017$Country, 'country.name', 'iso3c')


gdp2017<-cbind.data.frame(gdp2017, code1)
region2017<-cbind.data.frame(region2017, code2)
life2017<-cbind.data.frame(life2017, code4)
suicide2017<-cbind.data.frame(suicide2017, code3)
happy2017<-cbind.data.frame(happy2017, code5)

colnames(gdp2017)<-c("Country", "USGDP", "Code")
colnames(region2017)<-c("Country", "Region", "Code")
colnames(life2017)<-c("Country", "Life Expectancy", "Code")
colnames(suicide2017)<-c("Country", "BothSex", "Code")
colnames(happy2017)<-c("Country", "Score", "Code")


gdp2017<-select(gdp2017, Country, USGDP, Code)
life2017<-select(life2017, 'Life Expectancy', Code)
suicide2017<-select(suicide2017,  BothSex, Code)
region2017<-select(region2017,  Region, Code)
happy2017<-select(happy2017, Score, Code)


life2017$`Life Expectancy`<-gsub("years", "", life2017$`Life Expectancy`)

suicide2017$Country<-gsub('\\(', "", suicide2017$Country)
suicide2017$Country<-gsub('more info', "", suicide2017$Country)
suicide2017$Country<-gsub('\\)', "", suicide2017$Country)
suicide2017$Country<-gsub('\\*', "", suicide2017$Country)

merge2017<-data.frame()
merge2017<-left_join(gdp2017, region2017, by="Code")
merge2017<-left_join(merge2017, life2017, by="Code")
merge2017<-left_join(merge2017, suicide2017, by="Code")
merge2017<-left_join(merge2017, happy2017, by="Code")
merge2017$USGDP<-as.numeric(merge2017$USGDP)

attach(merge2017)


merge2017$`Life Expectancy`<-as.numeric(merge2017$`Life Expectancy`)
```


???????????? ????????? (x???: log(GDP), y???: Life Expectancy, Size : Suicide Rate, Color: Region)
```{r}
#bubblechart 

loggdp<-log(merge2017$USGDP)

bubble2017<-ggplot(merge2017, aes(loggdp, `Life Expectancy`)) + 
  geom_point(aes(size=BothSex, colour = Region)) +
  ggtitle("MERGE2017 Bubble Chart") +
  scale_y_continuous(breaks=seq(40,90,5)) +
  xlab("Log(USGDP)")

bubble2017

```

????????? ????????? ?????????
```{r}
#mapping 


datacode<-select(gdp2017, Country, Code)

world2017<-map_data("world")

merge2<-merge2017

w2017<-select(world2017, long, lat, region, group)
colnames(w2017)<-c("long", "lat", "Country", "group")
code10<-countrycode(w2017$Country, 'country.name', 'iso3c')
w2017<-cbind.data.frame(w2017, code10)

colnames(w2017)<-c("long", "lat", "Country", "group", "Code")

merge2<-left_join(merge2, w2017, by="Code")

ggmap2017<- ggplot(data=merge2) +
  geom_polygon(aes(x=long, y=lat, group=group, fill=BothSex)) +
  ggtitle("Map2017 Suicide Rate")

ggmap2017
```

